#!/bin/bash

################### VARIABLES ######################
USER=$(whoami)
KERNELVERSION=$(uname -r)
#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

clear
	echo -e "\e[38;5;4m                        |                              _ \                   |       _ \   _)   |  |"
	echo -e "\e[38;5;25m   __|   |   |    __|   __|    _ \    __ '__ \        |   |    _ \     __|   |  /   |   |   |   |  |"
	echo -e "\e[38;5;55m  (      |   |  \__ \   |     (   |   |   |   |       __ <    (   |   (        <    ___/    |  ___ __|"
	echo -e "\e[38;5;57m \___|  \__,_|  ____/  \__|  \___/   _|  _|  _|      _| \_\  \___/   \___|  _|\_\  _|      _|     _|"
sleep 1
	echo -e " The current User is: " "$USER" "\e[0m"
sleep 1
	echo




########## Install custom bashpromt?
while true
do
	echo -e "\e[48;5;57m Do you want to customize your bashpromt?\e[48;5;235m[Y/n]\e[0m"
	echo -e " The colors are like the colors in the custom RockPi4 banner above."
	read -r -p  " The temperature is also displayed in the promt." input
 case $input in
     [yY][eE][sS]|[yY])
	echo -e "\e[0m Installing..."
	cat ./files/bashrc_payload >> $HOME/.bashrc  
	echo -e " The changes are visible after a reboot. Or after this command: \e[48;5;57msource ~/.bashrc\e[0m"
	echo 
 break
	;;
     [nN][oO]|[nN])
echo " Not installed..."
	break
    ;;
     *)
	echo " Invalid input..."
	;;
 esac
done
#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx



########## Install Wireguard?
while true
do
	echo -e "\e[48;5;57m Do you want to install Wireguard VPN?\e[48;5;235m[Y/n]\e[0m"
	echo -e " RockPi4 Kernelheaders will be installed."
	read -r -p  " Wireguard dependencies will be installed." input
	case $input in
     [yY][eE][sS]|[yY])
	echo -e "\e[48;5;57m Updating packages now.\e[0m"
	apt-get -y update
	echo -e "\e[48;5;57m Upgrading packages now.\e[0m"
	apt-get -y upgrade
	echo -e "\e[48;5;57m Checking for kernel compatibility...\e[0m"
if [[ "${KERNELVERSION}" == *"rockchip64"* ]]; then ####### Compare Kernel wirh KernelHeaders
	echo -e "\e[48;5;57m The kernel headers match the installed kernel.\e[0m"
	apt-get -y install linux-headers-current-rockchip64
	echo -e "\e[48;5;57m Installing some lib's.\e[0m"
	apt-get -y install libmnl-dev libelf-dev build-essential pkg-config
	echo -e "\e[48;5;57m Finally installing Wireguard.\e[0m"
	apt-get -y install wireguard
else
	echo -e "\e[48;5;160m Something went wrong with the Kernel-headers! Please check it.                   \e[0m"
	echo -e "\e[48;5;160m Your installed Kernel is ${KERNELVERSION} but this installer is for the Rockchip64        \e[0m"
	echo -e "\e[48;5;160m This script was made 02.07.2020. If you have an RockPi4 and this does not work-  \e[0m"
	echo -e "\e[48;5;160m maby this installer is to old..                                                  \e[0m"
fi
 break
	;;
     [nN][oO]|[nN])
echo " Not installed..."
 break
    ;;
     *)
 echo " Invalid input..."
	;;
 esac
done
#xxxxxxxxxxxxxxxxxxxxxxxxxxxx



################### FUNCTIONS ######################
#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


