#!/bin/bash

################### VARIABLES ######################
USER=$(whoami)
#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
sudo -i
clear
	echo -e "\e[38;5;4m                        |                              _ \                   |       _ \   _)   |  |"
	echo -e "\e[38;5;25m   __|   |   |    __|   __|    _ \    __ '__ \        |   |    _ \     __|   |  /   |   |   |   |  |"
	echo -e "\e[38;5;55m  (      |   |  \__ \   |     (   |   |   |   |       __ <    (   |   (        <    ___/    |  ___ __|"
	echo -e "\e[38;5;57m \___|  \__,_|  ____/  \__|  \___/   _|  _|  _|      _| \_\  \___/   \___|  _|\_\  _|      _|     _|"
sleep 1
	echo -e " The current User is: " "$USER" "\e[0m"
sleep 1
	echo

sudo chmod +x ./scripts/1_install_wireguard
sudo chmod +x ./scripts/2_Install_MOTD


########## Install custom bashpromt?
while true
do
	echo -e "\e[48;5;57m Do you want to customize your bashpromt?\e[48;5;235m[Y/n]\e[0m"
	echo -e " The colors are like the colors in the custom RockPi4 banner above."
	read -r -p  " The temperature is also displayed in the promt." input
 case $input in
     [yY][eE][sS]|[yY])
	echo -e "\e[0m Installing..."
	sudo cat ./files/2payload_bashrc >> $HOME/.bashrc
	echo -e " The changes are visible after reconnecting to terminal. Or after this command: \e[48;5;57msource ~/.bashrc\e[0m"
	echo
 break
	;;
     [nN][oO]|[nN])
echo " Not installed..."
	break
    ;;
     *)
	echo " Invalid input..."
	;;
 esac
done
#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

########## Install custom MOTD?
while true
do
	echo -e "\e[48;5;57m Do you want to install a custom Message of the Day?\e[48;5;235m[Y/n]\e[0m"
	read -r -p  " Lolcat and figlet will be installed." input
	case $input in
     [yY][eE][sS]|[yY])
	sudo bash ./scripts/2_Install_MOTD

 break
	;;
     [nN][oO]|[nN])
echo " Not installed..."
 break
    ;;
     *)
 echo " Invalid input..."
	;;
 esac
done
#xxxxxxxxxxxxxxxxxxxxxxxxxxxx

########## Install Wireguard?
while true
do
	echo -e "\e[48;5;57m Do you want to install Wireguard VPN?\e[48;5;235m[Y/n]\e[0m"
	echo -e " RockPi4 Kernelheaders will be installed."
	read -r -p  " Wireguard dependencies will be installed." input
	case $input in
     [yY][eE][sS]|[yY])
	sudo bash ./scripts/1_install_wireguard

 break
	;;
     [nN][oO]|[nN])
echo " Not installed..."
 break
    ;;
     *)
 echo " Invalid input..."
	;;
 esac
done
#xxxxxxxxxxxxxxxxxxxxxxxxxxxx


########## Install PiHole?
while true
do
	echo -e "\e[48;5;57m Do you want to install PiHole?\e[48;5;235m[Y/n]\e[0m"
	read -r -p  " The script will be downloaded from https://install.pi-hole.net" input
	case $input in
     [yY][eE][sS]|[yY])
 	
	curl -sSL https://install.pi-hole.net | bash

 break
	;;
     [nN][oO]|[nN])
echo " Not installed..."
 break
    ;;
     *)
 echo " Invalid input..."
	;;
 esac
done
#xxxxxxxxxxxxxxxxxxxxxxxxxxxx




################### FUNCTIONS ######################
#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


