#!/bin/bash

########## Variables ##########
UPTIMEcut="$(uptime -p)"
UPTIMEcut=${UPTIMEcut/#*up}
########## /Variables #########

########## Print Header #######
figlet "       $(hostname)" | lolcat -f -a -s 90 -p 2 -S 1
echo "       is now up for$UPTIMEcut" | lolcat -f -a -s 50 -p 2 -S 10
########## /Print Header ######


# get load averages
IFS=" " read LOAD1 LOAD5 LOAD15 <<<$(cat /proc/loadavg | awk '{ print $1,$2,$3 }')
# get free memory
IFS=" " read USED FREE TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$4,$2'})
# get processes
PROCESS=`ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }'`
PROCESS_ALL=`echo "$PROCESS"| awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`
PROCESS_ROOT=`echo "$PROCESS"| grep root | awk {'print $2'}`
PROCESS_USER=`echo "$PROCESS"| grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`

W="\e[0m"
G="\e[38;5;85m"

echo -e "
${W}      System information:
$W       |__Processes: $G$PROCESS_ROOT$W (root), $G$PROCESS_USER$W (user), $G$PROCESS_ALL$W (total)
$W       |_____Memory: $G$USED$W used, $G$FREE$W free, $G$TOTAL$W total$W
$W       |_______Load: $G$LOAD1$W (1m), $G$LOAD5$W (5m), $G$LOAD15$W (15m)"









###########################
# config
max_usage=90
bar_width=46
# colors
white="\e[38;5;235m"
green="\e[38;5;57m"
red="\e[1;38;5;160m"
dim="\e[2m"
undim="\e[0m"

# disk usage: ignore zfs, squashfs & tmpfs
mapfile -t dfs < <(df -H -x zfs -x squashfs -x tmpfs -x devtmpfs -x overlay --output=target,pcent,size | tail -n+2)

printf "\n      disk usage:\n"
for line in "${dfs[@]}"; do
    # get disk usage
    usage=$(echo "$line" | awk '{print $2}' | sed 's/%//')
    used_width=$((($usage*$bar_width)/100))
    # color is green if usage < max_usage, else red
    if [ "${usage}" -ge "${max_usage}" ]; then
        color=$red
    else
        color=$green
    fi
    # print green/red bar until used_width
    bar="     ${color}"
    for ((i=0; i<$used_width; i++)); do
        bar+="█"
    done
    # print dimmmed bar until end
    bar+="${white}${dim}"
    for ((i=$used_width; i<$bar_width; i++)); do
        bar+="▄"
    done
    bar+="${undim}"
    # print usage line & bar

    echo "     |${line:1}" | awk '{ printf("%-36s%+3s used out of %+4s\n", $1, $2, $3); }' | sed -e 's/^/  /'
    echo -e "${bar}" | sed -e 's/^/  /'
done