#!/bin/bash



######## Variables
wgconf_exist='none'
#xxxxxxx /Variables

######## Check if wireguard is installed
pkgs='wireguard'
if ! dpkg -s $pkgs >/dev/null 2>&1; then
######## Install wireguard if not installed
 echo -e "\e[48;5;57m Wireguard is not installed. Do you want to install it?\e[48;5;235m[Y/n]\e[0m"
 read -r -p  " The installation script will be downloaded and executed." input
   case $input in
     [yY][eE][sS]|[yY])
	  echo -e "\e[0m Installing..."
      curl https://raw.githubusercontent.com/twerpyfie/CustomRP/master/scripts/1_install_wireguard | bash
      ;;
     [nN][oO]|[nN])
      echo " Not installed..."
	  ;;
      *)
	 echo " Invalid input..."
	 ;;
   esac
fi
#xxxxxxx /Check if wireguard is installed
######## Check if wg config/s (a wireguard network) exists

cd /etc/wireguard/
ext=conf
wgconf_exist=0
for i in *; do
    if [ "${i}" != "${i%.${ext}}" ];then
        ((++wgconf_exist))
    fi
done

count=1
if [ '${wgconf_exist}'>='${count}' ];then
echo wgconf exists
echo $wgconf_exist
fi



#check for files like wg0.conf in /etc/wireguard/
#i think wg*.conf
#when wg*.conf is there, list all networks and ask if you want to create a new or what else you can do with the configs 
#xxxxxxx /Check if wg config exists


#when config/network has to be created: check if ipv4 is enabled
# check if ipv4 is enabled 
# sysctl net.ipv4.ip_forward 
# if not, set it 
# perl -pi -e 's/#{1,}?net.ipv4.ip_forward ?= ?(0|1)/net.ipv4.ip_forward = 1/g' /etc/sysctl.conf 
# check if ipv4 is enabled, if not, the user has to make it manually
# reboot, or search for other soution to renew the sysctl.conf by running system

#when ipv4 stuff is done Generate private and public keys for server and client1 and configure the,server,network,interface whatever: /etc/wireguard/wg0.conf
#https://github.com/adrianmihalko/raspberrypiwireguard

#this is what i want:
#files:
#1 wg-add-peer  -,_ Maby a peermanager?
#2 wg-show-peer -'
#3 wg-network-manager
